# Generated by Django 3.1 on 2020-08-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='done',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
