# Generated by Django 3.1 on 2020-08-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_question_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='done',
        ),
    ]
