# Generated by Django 3.1 on 2020-08-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
