# Generated by Django 3.1 on 2020-08-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='user_id',
            new_name='user',
        ),
    ]
