# Generated by Django 2.2.6 on 2020-08-13 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200813_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='summary',
        ),
    ]
