# Generated by Django 2.2.6 on 2020-08-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='serial',
        ),
        migrations.AddField(
            model_name='course',
            name='dev_type',
            field=models.CharField(default='frontend', max_length=100),
            preserve_default=False,
        ),
    ]
