# Generated by Django 2.2.6 on 2020-08-15 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20200815_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='dev_type',
        ),
    ]
