# Generated by Django 2.2.6 on 2020-08-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20200816_0703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Devtype',
        ),
    ]
