# Generated by Django 2.2.6 on 2020-08-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_devtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='dev_type',
            new_name='devtype',
        ),
    ]
