# Generated by Django 2.2.6 on 2020-08-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20200816_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='devtype',
        ),
    ]
