# Generated by Django 2.2.6 on 2020-08-16 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_remove_course_devtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Devtype',
        ),
    ]
