# Generated by Django 2.2.6 on 2020-08-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_delete_devtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='tutors',
        ),
    ]
