# Generated by Django 2.2.6 on 2020-08-16 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_course_tutors'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='devtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Devtype'),
            preserve_default=False,
        ),
    ]
