# Generated by Django 2.2.6 on 2020-08-19 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_course_devtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tutors',
        ),
    ]
