# Generated by Django 2.2.6 on 2020-08-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_remove_course_tutors'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tutors',
            field=models.ManyToManyField(to='courses.Tutor'),
        ),
    ]
