# Generated by Django 2.2.6 on 2020-08-19 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_course_tutors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tutors',
        ),
    ]
