# Generated by Django 2.2.6 on 2020-08-21 13:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_remove_course_tutors'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='logo',
            field=cloudinary.models.CloudinaryField(default='test.jpg', max_length=255),
            preserve_default=False,
        ),
    ]
