# Generated by Django 2.2.6 on 2020-08-22 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_course_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='logo',
        ),
    ]
